### ISSUE TITLE
Cannot read property 'on' of undefined after updating @nativescript/core

### ISSUE THREAD

**Issue by bytesoverflow** [nativescript-community/appurl#13]
After updating @nativescript/core from version 8.1.1 to 8.2.3 the application will not launch on android.
It fails with the error `Cannot read property 'on' of undefined`

```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function
System.err: TypeError: Cannot read property 'on' of undefined
System.err: File: (file: src/webpack/bootstrap:27:0)
System.err:
System.err: StackTrace:
System.err: ./node_modules/@nativescript-community/appurl/urlhandler.android.js(file: node_modules/@nativescript-community/appurl/urlhandler.android.js:27:0)
System.err:     at __webpack_require__(file: src/webpack/bootstrap:24:0)
System.err:     at fn(file: src/webpack/runtime/hot module replacement:62:0)
System.err:     at ./src/main.ts(file:///data/data/com..mobile/files/app/bundle.js:18:88)
System.err:     at __webpack_require__(file: src/webpack/bootstrap:24:0)
System.err:     at __webpack_exec__(file:///data/data/com..mobile/files/app/bundle.js:9850:39)
System.err:     at (file:///data/data/com..mobile/files/app/bundle.js:9851:299)
System.err:     at (file: src/webpack/runtime/startup entrypoint:6:0)
System.err:     at (file:///data/data/com..mobile/files/app/bundle.js:9851:47)
System.err:     at (file:///data/data/com..mobile/files/app/bundle.js:9856:3)
System.err:     at require(:1:266)
```

**Comment by dartstyle** [comment]
I have the same issue with NS core 8.3.0
